steps:
- name: gcr.io/cloud-builders/docker
  id: Build Dbt Image
  args: [
      'build',
      '--network=cloudbuild',
      '-t', 'europe-docker.pkg.dev/$PROJECT_ID/dbt-modelling-demo',
      '--cache-from', 'europe-docker.pkg.dev/$PROJECT_ID/dbt-modelling-demo:latest',
      './dbt_quickstart/'
    ]

- name: gcr.io/cloud-builders/docker
  id: Push Dbt Image to the Repo
  args: [
      'push',
      'europe-docker.pkg.dev/$PROJECT_ID/dbt-modelling-demo:latest'
    ]

options:
  logging: CLOUD_LOGGING_ONLY